name: Gradle Build

on:
  push:
    branches: ["main", "beta", "develop"]
  pull_request:
    branches: ["main", "beta", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.8'

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run tests
        run: ./gradlew test

      - name: Build
        run: ./gradlew build
